# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttrDAS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nama_das', models.CharField(max_length=45)),
                ('kode', models.CharField(max_length=4)),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DAS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coordinates', models.BinaryField()),
                ('attr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.AttrDAS')),
            ],
        ),
    ]
