# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTeknik',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ca', models.FloatField()),
                ('luas_genangan', models.FloatField()),
                ('tipe_konstruksi', models.CharField(max_length=45)),
                ('volume', models.BigIntegerField()),
                ('luas', models.FloatField()),
                ('h_sungai', models.FloatField()),
                ('h_pondasi', models.FloatField()),
                ('lebar_spill', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fungsi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('irigasi', models.FloatField()),
                ('ternak', models.IntegerField()),
                ('air_baku', models.IntegerField()),
                ('pltm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desa', models.CharField(max_length=45)),
                ('kec', models.CharField(max_length=45)),
                ('kab', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Posisi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lang', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sungai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tahun_buat', models.CharField(max_length=4)),
                ('biaya', models.BigIntegerField()),
                ('keterangan', models.CharField(max_length=45)),
            ],
        ),
    ]
