# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_datateknik_fungsi_lokasi_posisi_sungai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sungai',
            new_name='Bendung',
        ),
    ]
