# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_auto_20170508_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='bendung',
            name='nama_bendung',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
    ]
